jobs:
  - name: aws-uc-feature-infrastructure-development
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-development
          - get: aws-uc-feature-infrastructure
            trigger: true
          - get: emr-launcher-release
            version: { tag: ((emr-launcher-version.development)) }
            trigger: true
          - get: emr-relauncher-release
            version: { tag: ((emr-relauncher-version.development)) }
            trigger: true
          - get: dataworks-behavioural-framework
            trigger: false
          - get: al2-emr-ami
            trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: default
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: default
