jobs:
  - name: update-pipeline
    plan:
      - get: aws-uc-feature
        resource: aws-uc-feature-pipeline
        trigger: true
      - task: aviator
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_aviator_repository))
              version: ((dataworks.docker_aviator_version))
          run:
            path: sh
            args:
              - -exc
              - |
                sed -i 's/fly/nofly/' aviator.yml
                /usr/bin/aviator -f aviator.yml
                mv aviator_pipeline.yml ../pipeline
                mv ci/vars.yml ../pipeline
            dir: aws-uc-feature
          inputs:
            - name: aws-uc-feature
          outputs:
            - name: pipeline
      - set_pipeline: aws-uc-feature
        file: pipeline/aviator_pipeline.yml
        var_files:
          - pipeline/vars.yml
